### ISSUE TITLE
Sample doesn't do anything, and crashes when pressing back button

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [StylingAndroid/Visualiser#1]
All I see is a blank activity (with title).
When pressing back, I get a crash, with this log:

01-31 22:52:57.254 12500-12500/com.stylingandroid.vizualiser E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.stylingandroid.vizualiser, PID: 12500
                                                                               java.lang.RuntimeException: Unable to pause activity {com.stylingandroid.vizualiser/com.stylingandroid.vizualiser.MainActivity}: java.lang.IllegalStateException: Unable to retrieve Visualizer pointer
                                                                                   at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3296)
                                                                                   at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3252)
                                                                                   at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3227)
                                                                                   at android.app.ActivityThread.access$1100(ActivityThread.java:154)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                                                Caused by: java.lang.IllegalStateException: Unable to retrieve Visualizer pointer
                                                                                   at android.media.audiofx.Visualizer.native_setPeriodicCapture(Native Method)
                                                                                   at android.media.audiofx.Visualizer.setDataCaptureListener(Visualizer.java:590)
                                                                                   at com.stylingandroid.vizualiser.MainActivity.onPause(MainActivity.java:81)
                                                                                   at android.app.Activity.performPause(Activity.java:6101)
                                                                                   at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1310)
                                                                                   at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3279)
                                                                                   at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3252) 
                                                                                   at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3227) 
                                                                                   at android.app.ActivityThread.access$1100(ActivityThread.java:154) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:135) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5294) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by billyjoker** [comment]
The same happens to me, always that reach onPause event, throws that

`{com.stylingandroid.vizualiser/com.stylingandroid.vizualiser.MainActivity}: java.lang.IllegalStateException: Unable to retrieve Visualizer pointer`

**Comment by ZafarQuaere** [comment]
As the heading is telling.. This sample really don't do any thing and crashing while pressing back button.
and getting the error as 
java.lang.IllegalStateException: Unable to retrieve Visualizer pointer

No, issue as the exception can be handled but what the sample is doing is not getting yet ?
